apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: <your-docker-image>
          ports:
            - containerPort: 80
            - containerPort: 443
          envFrom:
            - configMapRef:
                name: gateway-config
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/letsencrypt
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx/bot_cache
      volumes:
        - name: ssl-certs
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
