apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  AUTH_SERVICE_URL: "${AUTH_SERVICE_URL}"
  USERS_SERVICE_URL: "${USERS_SERVICE_URL}"
  ACTIVITIES_SERVICE_URL: "${ACTIVITIES_SERVICE_URL}"
  PRICING_SERVICE_URL: "${PRICING_SERVICE_URL}"
  PLANS_SERVICE_URL: "${PLANS_SERVICE_URL}"
  ROUTES_SERVICE_URL: "${ROUTES_SERVICE_URL}"
  BOT_SERVICE_URL: "${BOT_SERVICE_URL}"
  AUTH_CHECK_SERVICE_URL: "${AUTH_CHECK_SERVICE_URL}"
  DOMAIN_FOR_SSL: "${DOMAIN_FOR_SSL}"
  EMAIL_FOR_SSL: "${EMAIL_FOR_SSL}"