services:
  # PostgreSQL
  postgres:
    image: ${DOCKERHUB_NAMESPACE}/postgres:${POSTGRES_IMAGE_VERSION}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    secrets:
      - POSTGRES_PASS
      - POSTGRES_USER
      - DB_AUTH_SERVICE_NAME
      - DB_AUTH_SERVICE_PASS
      - DB_AUTH_SERVICE_USER
      - DB_PROFILE_SERVICE_NAME
      - DB_PROFILE_SERVICE_PASS
      - DB_PROFILE_SERVICE_USER
    environment:
      POSTGRES_PASS_FILE: /run/secrets/POSTGRES_PASS
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_INITDB_WALDIR: ""
      POSTGRES_MULTIPLE_DATABASES: auth,profile
      DB_AUTH_SERVICE_NAME_FILE: /run/secrets/DB_AUTH_SERVICE_NAME
      DB_AUTH_SERVICE_PASS_FILE: /run/secrets/DB_AUTH_SERVICE_PASS
      DB_AUTH_SERVICE_USER_FILE: /run/secrets/DB_AUTH_SERVICE_USER
      DB_PROFILE_SERVICE_NAME_FILE: /run/secrets/DB_PROFILE_SERVICE_NAME
      DB_PROFILE_SERVICE_PASS_FILE: /run/secrets/DB_PROFILE_SERVICE_PASS
      DB_PROFILE_SERVICE_USER_FILE: /run/secrets/DB_PROFILE_SERVICE_USER
    ports:
      - "${DB_PORT}:5432"
    networks:
      - data-network

  # Redis
  redis:
    image: redis:8.4.0-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - data-network

networks:
  data-network:
    external: true

volumes:
  postgres-data:

secrets:
  POSTGRES_PASS:
    external: true
  POSTGRES_USER:
    external: true
  DB_AUTH_SERVICE_NAME:
    external: true
  DB_AUTH_SERVICE_PASS:
    external: true
  DB_AUTH_SERVICE_USER:
    external: true
  DB_PROFILE_SERVICE_NAME:
    external: true
  DB_PROFILE_SERVICE_PASS:
    external: true
  DB_PROFILE_SERVICE_USER:
    external: true
  DB_LOCATION_SERVICE_NAME:
    external: true
  DB_LOCATION_SERVICE_PASS:
    external: true
  DB_LOCATION_SERVICE_USER:
    external: true
